# frozen_string_literal: true

# #Medical Network Professional Claims v3
#
# Reference for developers
#
# OpenAPI spec version: v3
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 2.4.19
#

module ChangeHealthcare
  module ProfessionalClaims
    module SwaggerClient
      VERSION = '1.0.0'
    end
  end
end
