# frozen_string_literal: true

# #Medical Network Professional Claims v3
#
# Reference for developers
#
# OpenAPI spec version: v3
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 2.4.19
#

# Common files
require_relative './swagger_client/api_client'
require_relative './swagger_client/api_error'
require_relative './swagger_client/version'
require_relative './swagger_client/configuration'

# Models
require_relative './swagger_client/models/address'
require_relative './swagger_client/models/ambulance_certification'
require_relative './swagger_client/models/ambulance_transport_information'
require_relative './swagger_client/models/clai_request'
require_relative './swagger_client/models/claim_adjustment'
require_relative './swagger_client/models/claim_adjustment_details'
require_relative './swagger_client/models/claim_contract_information'
require_relative './swagger_client/models/claim_date_information'
require_relative './swagger_client/models/claim_information'
require_relative './swagger_client/models/claim_note'
require_relative './swagger_client/models/claim_pricing_repricing_information'
require_relative './swagger_client/models/claim_reference'
require_relative './swagger_client/models/claim_submission_request'
require_relative './swagger_client/models/claim_supplemental_information'
require_relative './swagger_client/models/composite_diagnosis_code_pointers'
require_relative './swagger_client/models/condition_indicator_durable_medical_equipment'
require_relative './swagger_client/models/condition_information'
require_relative './swagger_client/models/contact_information'
require_relative './swagger_client/models/contract_information'
require_relative './swagger_client/models/dependent'
require_relative './swagger_client/models/drug_identification'
require_relative './swagger_client/models/durable_medical_equipment_certificate_of_medical_necessity'
require_relative './swagger_client/models/durable_medical_equipment_certification'
require_relative './swagger_client/models/durable_medical_equipment_service'
require_relative './swagger_client/models/edit_response'
require_relative './swagger_client/models/epsdt_referral'
require_relative './swagger_client/models/error'
require_relative './swagger_client/models/failure'
require_relative './swagger_client/models/form_identification'
require_relative './swagger_client/models/health_care_information'
require_relative './swagger_client/models/line_adjudication_information'
require_relative './swagger_client/models/measurements'
require_relative './swagger_client/models/medicare_outpatient_adjudication'
require_relative './swagger_client/models/other_payer_billing_provider'
require_relative './swagger_client/models/other_payer_name'
require_relative './swagger_client/models/other_payer_referring_provider'
require_relative './swagger_client/models/other_payer_rendering_provider'
require_relative './swagger_client/models/other_payer_service_facility_location'
require_relative './swagger_client/models/other_payer_supervising_provider'
require_relative './swagger_client/models/other_subscriber_information'
require_relative './swagger_client/models/other_subscriber_name'
require_relative './swagger_client/models/patient_condition_information_vision'
require_relative './swagger_client/models/pay_to_plan'
require_relative './swagger_client/models/payer'
require_relative './swagger_client/models/prior_authorization'
require_relative './swagger_client/models/professional_service'
require_relative './swagger_client/models/provider'
require_relative './swagger_client/models/purchased_service_information'
require_relative './swagger_client/models/raw_x12_request'
require_relative './swagger_client/models/receiver'
require_relative './swagger_client/models/reference_identification'
require_relative './swagger_client/models/report_information'
require_relative './swagger_client/models/response'
require_relative './swagger_client/models/service_facility_location'
require_relative './swagger_client/models/service_line'
require_relative './swagger_client/models/service_line_date_information'
require_relative './swagger_client/models/service_line_provider'
require_relative './swagger_client/models/service_line_reference_information'
require_relative './swagger_client/models/spinal_manipulation_service_information'
require_relative './swagger_client/models/submitter'
require_relative './swagger_client/models/subscriber'
require_relative './swagger_client/models/supporting_documentation'

# APIs
require_relative './swagger_client/professional_claims_api'

module ChangeHealthcare
  module ProfessionalClaims
    module SwaggerClient
      class << self
        # Customize default settings for the SDK using block.
        #   SwaggerClient.configure do |config|
        #     config.username = "xxx"
        #     config.password = "xxx"
        #   end
        # If no block given, return the default Configuration object.
        def configure
          if block_given?
            yield(Configuration.default)
          else
            Configuration.default
          end
        end
      end
    end
  end
end
